# Docker compose start container with env variables
services:
  local-db:
    image: mysql
    environment:
      - POSTGRES_USER=vikas
      - POSTGRES_PASSWORD=Admin@123
      - POSTGRES_DB=lmsdb
    ports:
      - "3306:3306"
    # volumes: # uncomment to persist data using bind mount
    # - ./data:/var/lib/mysql/data
    # volumes: # uncomment to persist data using named volume
    #   - local-db-data:/var/lib/mysql/data

  api-server:
    image: lms-public-api
    build: api/
    environment:
      - MODE=local
      - PORT=8080
      - DATABASE_URL=mysql://vikas:Admin@123@3.138.196.139:3306/lmsdb
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - local-db

  web-server:
    image: lms-web
    build: webapp/
    environment:
      - MODE=local
      - API_URL=http://api-server:8080
    ports:
      - "3000:80"
    depends_on:
      - api-server
# volumes:
#   local-db-data: # uncomment to persist data using named volume
